spring:
  application:
    name: CATALOG-SERVICE

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/laravel
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-bean-definition-overriding: true

server:
  port: 9003

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}
    home-page-url: http://localhost:${server.port}/swagger-ui/index.html # Main URL
    status-page-url: http://localhost:${server.port}/swagger-ui/index.html # Change status-page-url
    metadata-map:
      swagger-ui: http://localhost:${server.port}/swagger-ui/index.html

# Swagger UI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info



