spring:
  application:
    name: GATEWAY-SERVICE
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-SERVICE-USER
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/user/**
          filters:
            - AuthFilter

        - id: ACCOUNT-SERVICE-AUTH
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - AuthFilter

        - id: PRODUCT-SERVICE
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/product/**
          filters:
            - AuthFilter

  default-filters:
    - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
  globalcors:
    corsConfigurations:
      '[/**]':
        allowedOrigins: "*"
        allowedMethods: "*"
        allowedHeaders: "*"

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/

